apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: collectds.collectd.barometer.com
  annotations:
    composition: Daemonset, Configmap
spec:
  group: collectd.barometer.com
  names:
    kind: Collectd
    listKind: CollectdList
    plural: collectds
    singular: collectd
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
