apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: collectds.collectd.barometer.com
  annotations:
    composition: Daemonset, Configmap
spec:
  group:  collectd.barometer.com
  names:
    kind: Collectd
    listKind: CollectdList
    plural: collectds
    singular: collectd
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      required:
        - spec
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            deploymentPlan:
              type: object
              properties:
                image:
                  type: string
                  description: The image used for the collectd deployment
                size:
                  type: integer
                  minimum: 1
                  maximum: 1
                  description: The number of Daemonset pods to deploy
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
