apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: collectd-resources
      namespace: operator-lifecycle-manager
    data:
      clusterServiceVersions: |
        - apiVersion: operators.coreos.com/v1alpha1
          kind: ClusterServiceVersion
          metadata:
            annotations:
              alm-examples: '[{"apiVersion":"collectd.barometer.com/v1alpha1","kind":"Collectd","metadata":{"labels":{"app":"collectd"},"name":"barometer-collectd-ds"},"spec":{"deploymentPlan":{"configname":"collectd-ds-config","image":"opnfv/barometer-collectd","size":1}}}]'
              capabilities: Basic Install
            name: barometer-operator.v0.1.0
            namespace: placeholder
          spec:
            apiservicedefinitions: {}
            customresourcedefinitions:
              owned:
              - kind: Collectd
                name: collectds.collectd.barometer.com
                version: v1alpha1
            description: Placeholder description
            displayName: Barometer Operator
            install:
              spec:
                deployments:
                - name: barometer-operator
                  spec:
                    replicas: 1
                    selector:
                      matchLabels:
                        name: barometer-operator
                    strategy: {}
                    template:
                      metadata:
                        labels:
                          name: barometer-operator
                      spec:
                        containers:
                        - command:
                          - barometer-operator
                          env:
                          - name: WATCH_NAMESPACE
                            valueFrom:
                              fieldRef:
                                fieldPath: metadata.annotations['olm.targetNamespaces']
                          - name: POD_NAME
                            valueFrom:
                              fieldRef:
                                fieldPath: metadata.name
                          - name: OPERATOR_NAME
                            value: barometer-operator
                          image: quay.io/aneeshkp/barometer-operator:v2.1.1
                          imagePullPolicy: Always
                          name: barometer-operator
                          resources: {}
                        serviceAccountName: barometer-operator
                permissions:
                - rules:
                  - apiGroups:
                    - ""
                    resources:
                    - pods
                    - services
                    - serviceaccounts
                    - endpoints
                    - persistentvolumeclaims
                    - events
                    - configmaps
                    - secrets
                    verbs:
                    - '*'
                  - apiGroups:
                    - ""
                    resources:
                    - namespaces
                    verbs:
                    - get
                  - apiGroups:
                    - apps
                    resources:
                    - deployments
                    - daemonsets
                    - replicasets
                    - statefulsets
                    verbs:
                    - '*'
                  - apiGroups:
                    - monitoring.coreos.com
                    resources:
                    - servicemonitors
                    verbs:
                    - get
                    - create
                  - apiGroups:
                    - apps
                    resourceNames:
                    - barometer-operator
                    resources:
                    - deployments/finalizers
                    verbs:
                    - update
                  - apiGroups:
                    - collectd.barometer.com
                    resources:
                    - '*'
                    verbs:
                    - '*'
                  serviceAccountName: barometer-operator
              strategy: deployment
            installModes:
            - supported: true
              type: OwnNamespace
            - supported: true
              type: SingleNamespace
            - supported: false
              type: MultiNamespace
            - supported: true
              type: AllNamespaces
            maturity: alpha
            provider: {}
            version: 0.1.0
      customResourceDefinitions: |
        - apiVersion: apiextensions.k8s.io/v1beta1
          kind: CustomResourceDefinition
          metadata:
            name: collectds.collectd.barometer.com
            annotations:
              composition: Daemonset, Configmap
          spec:
            group:  collectd.barometer.com
            names:
              kind: Collectd
              listKind: CollectdList
              plural: collectds
              singular: collectd
            scope: Namespaced
            subresources:
              status: {}
            validation:
              openAPIV3Schema:
                required:
                  - spec
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  metadata:
                    type: object
                  spec:
                    type: object
                    properties:
                      deploymentPlan:
                        type: object
                        properties:
                          image:
                            type: string
                            description: The image used for the collectd deployment
                          size:
                            type: integer
                            minimum: 1
                            maximum: 1
                            description: The number of Daemonset pods to deploy
                          configname:
                            type: string
                            description: THe name of collectd configmap
                        required:
                        - configname
                        - image  
                  status:
                    type: object
                    required:
                      - conditions
                    properties:
                      revNumber:
                        type: string
                      pods:
                        items:
                          type: string
                        type: array
                      phase:
                        type: string
                      conditions:
                        description: Conditions keeps most recent collectd conditions
                        items:
                          properties:
                            reason:
                              type: string
                            transitionTime:
                              format: date-time
                              type: object
                            type:
                              type: string
                          required:
                          - type
                          type: object
                        type: array
            version: v1alpha1
            versions:
            - name: v1alpha1
              served: true
              storage: true
            additionalPrinterColumns:
              - name: Replicas
                type: integer
                description: The number of collectd launched by the operator
                JSONPath: .spec.deploymentPlan.size
              - name: Image
                type: string
                JSONPath: .spec.deploymentPlan.image
              - name: ConfigName
                type: string
                JSONPath: .spec.deploymentPlan.configname
      packages: >
        - #! package-manifest: deploy/olm-catalog/barometer-operator/0.1.0/barometer-operator.v0.1.0.clusterserviceversion.yaml
          packageName: barometer-operator
          channels:
            - name: beta
              currentCSV: barometer-operator.v0.1.0

  - apiVersion: operators.coreos.com/v1alpha1
    kind: CatalogSource
    metadata:
      name: collectd-resources
      namespace: operator-lifecycle-manager
    spec:
      configMap: collectd-resources
      displayName: Barometer Collectd Operators
      publisher: Red Hat
      sourceType: internal
    status:
      configMapReference:
        name: collectd-resources
        namespace: operator-lifecycle-manager
