apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: barometer-resources
      namespace: operator-lifecycle-manager
    data:
      clusterServiceVersions: |
        - apiVersion: operators.coreos.com/v1alpha1
          kind: ClusterServiceVersion
          metadata:
            annotations:
              alm-examples: '[{"apiVersion":"collectd.opnfv.org/v1alpha1","kind":"Barometer","metadata":{"labels":{"app":"barometer"},"name":"barometer-collectd-ds"},"spec":{"deploymentPlan":{"configname":"barometer-config","image":"opnfv/barometer-collectd","size":1}}}]'
              capabilities: Basic Install
            name: barometer-operator.v0.1.0
            namespace: placeholder
          spec:
            apiservicedefinitions: {}
            customresourcedefinitions:
              owned:
              - kind: Barometer
                name: barometers.collectd.opnfv.org
                version: v1alpha1
            description: Placeholder description
            displayName: Barometer Operator
            install:
              spec:
                deployments:
                - name: barometer-operator
                  spec:
                    replicas: 1
                    selector:
                      matchLabels:
                        name: barometer-operator
                    strategy: {}
                    template:
                      metadata:
                        labels:
                          name: barometer-operator
                      spec:
                        containers:
                        - command:
                          - barometer-operator
                          env:
                          - name: WATCH_NAMESPACE
                            valueFrom:
                              fieldRef:
                                fieldPath: metadata.annotations['olm.targetNamespaces']
                          - name: POD_NAME
                            valueFrom:
                              fieldRef:
                                fieldPath: metadata.name
                          - name: OPERATOR_NAME
                            value: barometer-operator
                          image: quay.io/aneeshkp/barometer-operator:v2.1.1
                          imagePullPolicy: Always
                          name: barometer-operator
                          resources: {}
                        serviceAccountName: barometer-operator
                permissions:
                - rules:
                  - apiGroups:
                    - ""
                    resources:
                    - pods
                    - services
                    - serviceaccounts
                    - endpoints
                    - persistentvolumeclaims
                    - events
                    - configmaps
                    - secrets
                    verbs:
                    - '*'
                  - apiGroups:
                    - ""
                    resources:
                    - namespaces
                    verbs:
                    - get
                  - apiGroups:
                    - apps
                    resources:
                    - deployments
                    - daemonsets
                    - replicasets
                    - statefulsets
                    verbs:
                    - '*'
                  - apiGroups:
                    - monitoring.coreos.com
                    resources:
                    - servicemonitors
                    verbs:
                    - get
                    - create
                  - apiGroups:
                    - apps
                    resourceNames:
                    - barometer-operator
                    resources:
                    - deployments/finalizers
                    verbs:
                    - update
                  - apiGroups:
                    - collectd.opnfv.org
                    resources:
                    - '*'
                    verbs:
                    - '*'
                  serviceAccountName: barometer-operator
              strategy: deployment
            installModes:
            - supported: true
              type: OwnNamespace
            - supported: true
              type: SingleNamespace
            - supported: false
              type: MultiNamespace
            - supported: true
              type: AllNamespaces
            maturity: alpha
            provider: {}
            version: 0.1.0
      customResourceDefinitions: |
        - apiVersion: apiextensions.k8s.io/v1beta1
          kind: CustomResourceDefinition
          metadata:
            name: barometers.collectd.opnfv.org
          spec:
            group: collectd.opnfv.org
            names:
              kind: Barometer
              listKind: BarometerList
              plural: barometers
              singular: barometer
            scope: Namespaced
            subresources:
              status: {}
            validation:
              openAPIV3Schema:
                description: Barometer is the Schema for the barometers API
                properties:
                  apiVersion:
                    description: 'APIVersion defines the versioned schema of this representation
                      of an object. Servers should convert recognized schemas to the latest
                      internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
                    type: string
                  kind:
                    description: 'Kind is a string value representing the REST resource this
                      object represents. Servers may infer this from the endpoint the client
                      submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                    type: string
                  metadata:
                    type: object
                  spec:
                    description: BarometerSpec defines the desired state of Barometer
                    type: object
                    properties:
                      deploymentPlan:
                        type: object
                        properties:
                          image:
                            type: string
                            description: The image used for the collectd deployment
                          size:
                            type: integer
                            minimum: 1
                            maximum: 1
                            description: The number of Daemonset pods to deploy
                          configname:
                            type: string
                            description: THe name of collectd configmap
                        required:
                          - configname
                          - image
                  status:
                    description: BarometerStatus defines the observed state of Barometer
                    type: object
                    required:
                      - conditions
                type: object
            version: v1alpha1
            versions:
            - name: v1alpha1
              served: true
              storage: true
            additionalPrinterColumns:
              - name: Replicas
                type: integer
                description: The number of barometer launched by the operator
                JSONPath: .spec.deploymentPlan.size
              - name: Image
                type: string
                JSONPath: .spec.deploymentPlan.image
              - name: ConfigName
                type: string
                JSONPath: .spec.deploymentPlan.configname
      packages: >
        - #! package-manifest: deploy/olm-catalog/barometer-operator/0.1.0/barometer-operator.v0.1.0.clusterserviceversion.yaml
          packageName: barometer-operator
          channels:
            - name: beta
              currentCSV: barometer-operator.v0.1.0

  - apiVersion: operators.coreos.com/v1alpha1
    kind: CatalogSource
    metadata:
      name: barometer-resources
      namespace: operator-lifecycle-manager
    spec:
      configMap: barometer-resources
      displayName: Barometer Operator
      publisher: Red Hat
      sourceType: internal
    status:
      configMapReference:
        name: barometer-resources
        namespace: operator-lifecycle-manager
