apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: barometer-operator
subjects:
- kind: ServiceAccount
  namespace: default
  name: barometer-operator
roleRef:
  kind: ClusterRole
  name: barometer-operator
  apiGroup: rbac.authorization.k8s.io