apiVersion: apps/v1
kind: Deployment
metadata:
  name: barometer-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: barometer-operator
  template:
    metadata:
      labels:
        name: barometer-operator
    spec:
      serviceAccountName: barometer-operator
      containers:
        - name: barometer-operator
          # Replace this with the built image name
          #image: quay.io/aneeshkp/barometer-operator:latest
          image: REPLACE_IMAGE
          command:
          - barometer-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "barometer-operator"
