kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: barometer-operator-rolebinding
subjects:
- kind: ServiceAccount
  name: barometer-operator
roleRef:
  kind: Role
  name: barometer-operator-role
  apiGroup: rbac.authorization.k8s.io
