kind: ConfigMap
apiVersion: v1
metadata:
  name: barometer-config
  namespace: default
data:
  node.barometer.config: |-

    FQDNLookup fase

    LoadPlugin syslog

    <Plugin syslog>

       LogLevel debug

    </Plugin>


    LoadPlugin cpu

    LoadPlugin memory

    LoadPlugin logfile
    
    <Plugin "logfile">
      LogLevel "info"
      File "\/var\/log\/collectd.log"
      Timestamp true
    </Plugin>

    <Plugin "cpu">

      Interval 20

      ReportByState false

      ReportByCpu false

    </Plugin>




    <Plugin "memory">

      Interval 30

      ValuesAbsolute true

      ValuesPercentage true

    </Plugin>

    LoadPlugin processes
    <Plugin " processes">
      Process "docker"
    # Add any other processes you wish to monitor...
    </Plugin>
 
    #Last line (collectd requires ‘\n’ at the last line)
