kind: ConfigMap

apiVersion: v1

metadata:

  name: collectd-config

  namespace: default

data:

  node-collectd.conf: |-

    FQDNLookup false

    LoadPlugin syslog

    <Plugin syslog>

       LogLevel info

    </Plugin>


    LoadPlugin cpu

    LoadPlugin memory

    
    <Plugin "cpu">

      Interval 5

      ReportByState false

      ReportByCpu false

    </Plugin>




    <Plugin "memory">

      Interval 30

      ValuesAbsolute false

      ValuesPercentage true

    </Plugin>

    LoadPlugin processes
    <Plugin " processes">
      Process "docker"
    # Add any other processes you wish to monitor...
    </Plugin>
 
    #Last line (collectd requires ‘\n’ at the last line)