apiVersion: extensions/v1beta1

kind: DaemonSet

metadata:

  name: barometer-node-agent

  labels:

    app: barometer-node-agent

spec:

  template:

    metadata:

      labels:

        name: barometer-node-agent

    spec:

      hostNetwork: true

    
      containers:

      - name: barometer

        image: opnfv/barometer-collectd
        #command: ["/opt/collectd/sbin/collectd"]
        #args: ["-f", "-C","/etc/collectd/collectd.conf"]
        securityContext:
          privileged: true

        volumeMounts:
        - name: barometer-config-volume
          mountPath: /opt/collectd/etc/ 
          #mountPath: /etc/collectd

        #- name: proc

        #  mountPath: /hostfs

        #  readOnly: true

        #- name: etc

        #  mountPath: /mnt/etc

        #  readOnly: true

      volumes:
      - name: barometer-config-volume
        configMap:
          name: barometer-config
          items:
          - key: node-barometer.conf
            path: collectd.conf

      #- name: proc

      #  hostPath:

      #    path: /proc

      #- name: root

      #  hostPath:

      #    path: /

#      - name: etc

#        hostPath:

#           path: /etc

#      - name: opt

#        hostPath:

#          path: /opt
